### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'get_include'

### ISSUE THREAD

**Issue by basharovV** [MTG/homebrew-essentia#20] opened 2020-02-17 09:37 UTC
I'm trying to install Essentia and getting the following error: 

```
==> Installing essentia from mtg/essentia
==> Cloning https://github.com/MTG/essentia.git
Updating /Users/slav/Library/Caches/Homebrew/essentia--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0a17738 Merge branch 'master' of github.com:MTG/essentia
Entering 'test/audio'
Entering 'test/models'
/Users/slav/Library/Caches/Homebrew/essentia--git/test/audio
/Users/slav/Library/Caches/Homebrew/essentia--git/test/models
==> python3 waf configure --mode=release --with-examples --with-vamp --prefix=/usr/local/Cellar/essentia/HEAD-
==> python3 waf
==> python3 waf install
==> python3 waf configure --mode=release --only-python --prefix=/usr/local/Cellar/essentia/HEAD-0a17738
==> python3 waf
Last 15 lines from /Users/slav/Library/Logs/Homebrew/essentia/05.python3:
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/.waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2/waflib/Build.py", line 96, in execute_build
    self.recurse([self.run_dir])
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/.waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/wscript", line 315, in build
    ctx.recurse('src')
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/.waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/src/wscript", line 456, in build
    ctx.recurse('python')
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/.waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/private/tmp/essentia-20200217-87790-1s8oxy4/src/python/wscript", line 45, in build
    __import__('numpy').get_include(),
AttributeError: module 'numpy' has no attribute 'get_include'
```

**Comment by basharovV** [comment] 2020-02-27 10:42
@dbogdanov Is this somehow related to the dropped python2 support in https://github.com/MTG/homebrew-essentia/commit/136a9ed44f0ef0d810d960561bf06194cc5e8f1e ?

**Comment by solleo** [comment] 2020-02-27 13:52
Same error here (#21)

**Comment by CarltonS13** [comment] 2020-04-28 21:06
So I had this problem and I fixed it by running  "brew doctor" in the terminal,  which told me to fix my path and link numpy.

**Comment by dbogdanov** [comment] 2020-05-28 22:33
Cannot reproduce, closing.

**Closed as completed by dbogdanov** 2020-05-28 22:33 UTC
